---
- name: Install postgres
  apt: name="{{item}}" state=present
  with_items:
    - "postgresql"
    - "postgresql-client"
    - "python-psycopg2"

- name: ensure database is created
  postgresql_db: name={{ config.dbname }}
  become: yes
  become_user: postgres

- name: ensure user has access to database
  postgresql_user: db={{ config.dbname }} name={{ config.dbuser }} password={{ config.dbpassword }} priv=ALL
  become: yes
  become_user: postgres

- name: ensure user does not have unnecessary privilege
  postgresql_user: name={{ config.dbuser }} role_attr_flags=NOSUPERUSER,NOCREATEDB
  become: yes
  become_user: postgres
