---
- name: Install mysql
  apt: name="{{item}}" state=present
  with_items:
    - "mysql-server"
    - "mysql-client"
    - "python-mysqldb"

- name: ensure database is created
  mysql_db: name={{ config.dbname }}

- name: create db user
  mysql_user:
    name: "{{ config.dbuser }}"
    password: "{{ config.dbpassword }}"
    priv: "{{ config.dbname }}.*:ALL"
    state: present

