---
- name: Install nginx
  apt: name=nginx state=present

- name: Copy nginx configuration
  template: src=default.conf dest=/etc/nginx/sites-available/default.conf
  notify: restart nginx

- name: Symlink nginx config
  file:
    src: /etc/nginx/sites-available/default.conf
    dest: /etc/nginx/sites-enabled/default.conf
    state: link

- name: Remove default config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
